# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('company_name', models.CharField(default='guest', max_length=40)),
                ('details', models.CharField(default='guest', max_length=10000)),
                ('user_name', models.CharField(default='guest', max_length=20)),
                ('application_text', models.CharField(max_length=100000, primary_key=True, serialize=False)),
                ('email_user', models.EmailField(default='kunal716338@gmail.com', max_length=254)),
                ('pay_expected', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('company_name', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=100000, primary_key=True, serialize=False)),
                ('pay', models.IntegerField(default=0)),
                ('deadline', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='JobProvider',
            fields=[
                ('company_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobsCompleted',
            fields=[
                ('company_name', models.CharField(default='guest', max_length=40)),
                ('user_name', models.CharField(default='guest', max_length=20)),
                ('pay_given', models.IntegerField(default=0)),
                ('details', models.CharField(default='abcd', max_length=100000, primary_key=True, serialize=False)),
                ('date_accepted', models.DateTimeField(verbose_name='date accepted')),
                ('deadline', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('contact_number', models.IntegerField(default=0)),
                ('img', models.ImageField(blank=True, default='media/default.png', height_field='height_field', null=True, upload_to='media/', width_field='width_field')),
                ('website_linked', models.URLField(default='No Website Linked')),
                ('height_field', models.IntegerField(default=100, null=True)),
                ('width_field', models.IntegerField(default=100, null=True)),
                ('user_introduction', models.CharField(default='No Introduction Added', max_length=20000)),
            ],
        ),
    ]
